# Generated by Django 2.0.5 on 2018-06-01 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('generation_id', models.IntegerField(blank=True, null=True)),
                ('is_main_series', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'abilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoveMethods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'move_methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('generation_id', models.IntegerField(blank=True, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('damage_class_id', models.IntegerField(blank=True, null=True)),
                ('effect_id', models.IntegerField(blank=True, null=True)),
                ('effect_chance', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('species_id', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('base_experience', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pokemon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('damage_class_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('is_battle_only', models.IntegerField(blank=True, null=True)),
                ('game_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('generation_id', models.IntegerField(blank=True, null=True)),
                ('damage_class_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonAbilities',
            fields=[
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pokedex.Pokemon')),
                ('slot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pokemon_abilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonMoves',
            fields=[
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pokedex.Pokemon')),
                ('level', models.IntegerField()),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pokemon_moves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonStats',
            fields=[
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pokedex.Pokemon')),
                ('base_stat', models.IntegerField(blank=True, null=True)),
                ('effort', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pokemon_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonTypes',
            fields=[
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pokedex.Pokemon')),
                ('slot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pokemon_types',
                'managed': False,
            },
        ),
    ]
